name: Release

on:
    push:
        branches:
            - main

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Run Release Please
              uses: google-github-actions/release-please-action@v4
              with:
                  release-type: simple
                  package-name: interactive-menu
                  changelog-types: |
                      [
                          {"type":"feat","section":"Features","hidden":false},
                          {"type":"fix","section":"Bug Fixes","hidden":false},
                          {"type":"docs","section":"Documentation","hidden":false},
                          {"type":"chore","section":"Chores","hidden":true}
                      ]
